apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-app
  namespace: psql
spec:
  project: default
  source:
    repoURL: 'https://github.com/marco4test/argocd.git'
    targetRevision: HEAD
    path: manifest/postgres/helm
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
