piVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: bitnami/postgresql:14.1.0
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRESQL_PASSWORD
              value: {{ .Values.postgresqlPassword }}
            - name: POSTGRESQL_DATABASE
              value: {{ .Values.postgresqlDatabase }}
          volumeMounts:
            - mountPath: /bitnami/postgresql
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc