apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: storage
  resources:
    requests:
      storage: 10Gi
